"""EvoVM: a small stack-based virtual machine that executes generated bytecode."""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional

from compiler.codegen.bytecode import BINARY, BProgram, const_text
from compiler.runtime import EvoRuntimeError, binary_op, default_value, format_value, unary_op

MAX_CALL_DEPTH = 200


@dataclass
class VMResult:
    status: str                    # HALTED | RUNTIME_ERROR | STEP_LIMIT
    output: List[str]
    return_value: Any = None
    has_return: bool = False
    error_kind: Optional[str] = None
    error_message: Optional[str] = None
    executed: int = 0
    max_stack: int = 0
    max_call_depth: int = 0
    elapsed_ms: float = 0.0
    trace: List[dict] = field(default_factory=list)
    trace_truncated: bool = False
    globals_state: Dict[str, Any] = field(default_factory=dict)

    def summary(self) -> dict:
        return {
            "status": self.status, "output": "\n".join(self.output), "outputLines": self.output,
            "returnValue": format_value(self.return_value) if self.has_return else None,
            "error": f"{self.error_kind}: {self.error_message}" if self.error_kind else None,
            "executed": self.executed, "maxStack": self.max_stack, "maxCallDepth": self.max_call_depth,
            "elapsedMs": round(self.elapsed_ms, 4),
        }


def _fmt(v: Any) -> str:
    return const_text(v)


class EvoVM:
    def __init__(self, program: BProgram, step_limit: int = 1_000_000, trace_limit: int = 2000):
        self.p = program
        self.step_limit = step_limit
        self.trace_limit = trace_limit

    def run(self, trace: bool = False) -> VMResult:
        p = self.p
        code = p.code
        stack: List[Any] = []
        frames: List[dict] = []
        globals_: Dict[str, Any] = {g["name"]: default_value(g["type"]) for g in p.globals}
        out: List[str] = []
        tr: List[dict] = []
        truncated = False
        pc = 0
        cur_locals: List[Any] = []
        cur_fn = "<boot>"
        executed = max_stack = max_depth = 0
        status, kind, msg = "HALTED", None, None
        t0 = time.perf_counter()
        try:
            while True:
                ins = code[pc]
                op = ins.op
                executed += 1
                if executed > self.step_limit:
                    status, kind, msg = "STEP_LIMIT", "StepLimit", f"exceeded {self.step_limit} instructions"
                    break
                npc = pc + 1
                if op == "PUSH":
                    stack.append(ins.arg)
                elif op == "LOAD":
                    v = cur_locals[ins.arg]
                    if v is None:
                        raise EvoRuntimeError("UninitializedVariable", f"local slot {ins.arg_text} read before assignment")
                    stack.append(v)
                elif op == "STORE":
                    cur_locals[ins.arg] = stack.pop()
                elif op == "GLOAD":
                    stack.append(globals_[ins.arg])
                elif op == "GSTORE":
                    globals_[ins.arg] = stack.pop()
                elif op in BINARY:
                    b = stack.pop()
                    a = stack.pop()
                    stack.append(binary_op(op, a, b))
                elif op in ("NEG", "NOT", "I2F"):
                    stack.append(unary_op(op, stack.pop()))
                elif op == "JUMP":
                    npc = ins.arg
                elif op == "JUMP_IF_FALSE":
                    if not stack.pop():
                        npc = ins.arg
                elif op == "CALL":
                    fn = p.functions[ins.arg]
                    if len(frames) + 1 > MAX_CALL_DEPTH:
                        raise EvoRuntimeError("StackOverflow", f"call depth exceeded {MAX_CALL_DEPTH}")
                    argc = ins.arg2 or 0
                    args = stack[len(stack) - argc:] if argc else []
                    if argc:
                        del stack[len(stack) - argc:]
                    frames.append({"locals": cur_locals, "ret": pc + 1, "fn": cur_fn, "base": len(stack)})
                    cur_locals = args + [None] * (fn.nlocals - argc)
                    cur_fn = fn.name
                    npc = fn.entry
                    max_depth = max(max_depth, len(frames))
                elif op in ("RETURN", "RETURN_VOID"):
                    val = stack.pop() if op == "RETURN" else None
                    fr = frames.pop()
                    del stack[fr["base"]:]
                    cur_locals, cur_fn, npc = fr["locals"], fr["fn"], fr["ret"]
                    if op == "RETURN":
                        stack.append(val)
                elif op == "PRINT":
                    out.append(format_value(stack.pop()))
                elif op == "POP":
                    stack.pop()
                elif op == "HALT":
                    if trace and len(tr) < self.trace_limit:
                        tr.append({"step": executed, "pc": pc, "text": ins.text(), "function": cur_fn,
                                   "stack": [_fmt(x) for x in stack], "irId": ins.ir_id})
                    break
                else:
                    raise EvoRuntimeError("InvalidInstruction", f"unknown opcode {op}")
                if len(stack) > max_stack:
                    max_stack = len(stack)
                if trace:
                    if len(tr) < self.trace_limit:
                        tr.append({"step": executed, "pc": pc, "text": ins.text(), "function": ins.fn,
                                   "stack": [_fmt(x) for x in stack], "irId": ins.ir_id})
                    else:
                        truncated = True
                pc = npc
        except EvoRuntimeError as e:
            status, kind, msg = "RUNTIME_ERROR", e.kind, e.message
        except (IndexError, KeyError) as e:
            status, kind, msg = "RUNTIME_ERROR", "VMFault", f"{type(e).__name__}: {e}"
        elapsed = (time.perf_counter() - t0) * 1000
        has_ret = status == "HALTED" and len(stack) > 0
        return VMResult(status, out, stack[-1] if has_ret else None, has_ret, kind, msg, executed,
                        max_stack, max_depth, elapsed, tr, truncated, globals_)
